// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    ChatGPTModal: typeof import('./components/ChatGPTModal.vue')['default']
    CVPreview: typeof import('./components/CVPreview.vue')['default']
    CVPreviewSection: typeof import('./components/CVPreviewSection.vue')['default']
    DeleteBlockModal: typeof import('./components/DeleteBlockModal.vue')['default']
    Dropdown: typeof import('./components/Dropdown.vue')['default']
    DropdownMenu: typeof import('./components/DropdownMenu.vue')['default']
    Editor: typeof import('./components/Editor.vue')['default']
    FeedbackModal: typeof import('./components/FeedbackModal.vue')['default']
    Footer: typeof import('./components/Footer.vue')['default']
    Header: typeof import('./components/Header.vue')['default']
    IconEditor: typeof import('./components/IconEditor.vue')['default']
    IconElement: typeof import('./components/IconElement.vue')['default']
    Loading: typeof import('./components/Loading.vue')['default']
    Modal: typeof import('./components/Modal.vue')['default']
    MoreActions: typeof import('./components/MoreActions.vue')['default']
    Note: typeof import('./components/Note.vue')['default']
    Notification: typeof import('./components/Notification.vue')['default']
    PaymentModal: typeof import('./components/PaymentModal.vue')['default']
    README: typeof import('./components/README.md')['default']
    Sidebar: typeof import('./components/Sidebar.vue')['default']
    SidebarMenu: typeof import('./components/SidebarMenu.vue')['default']
    Title: typeof import('./components/Title.vue')['default']
    ToggleSwitch: typeof import('./components/ToggleSwitch.vue')['default']
    Toolbar: typeof import('./components/Toolbar.vue')['default']
    Tooltip: typeof import('./components/Tooltip.vue')['default']
  }
}

export { }
